#!/bin/bash

# let's get the radio working!
git checkout -- proprietary/vendor/lib64/libsettings.so
git checkout -- proprietary/vendor/lib64/libcneapiclient.so

# camera hax
git checkout -- proprietary/bin/mm-qcamera-daemon
git checkout -- proprietary/lib/hw/camera.msm8998.so
git checkout -- proprietary/lib/libMiCameraHal.so
git checkout -- proprietary/lib/libmm-qcamera.so
git checkout -- proprietary/lib/libmmcamera_interface.so
git checkout -- proprietary/lib/libmmjpeg_interface.so
git checkout -- proprietary/lib/libmorpho_memory_allocator.so
git checkout -- proprietary/lib/libmorpho_panorama.so
git checkout -- proprietary/lib/libqomx_core.so
git checkout -- proprietary/vendor/lib/lib_lowlight.so
git checkout -- proprietary/vendor/lib/libarcsoft_beauty_shot.so
git checkout -- proprietary/vendor/lib/libarcsoft_beautyshot.so
git checkout -- proprietary/vendor/lib/libarcsoft_beautyshot_image_algorithm.so
git checkout -- proprietary/vendor/lib/libarcsoft_beautyshot_video_algorithm.so
git checkout -- proprietary/vendor/lib/libarcsoft_dualcam_optical_zoom.so
git checkout -- proprietary/vendor/lib/libarcsoft_dualcam_optical_zoom_control.so
git checkout -- proprietary/vendor/lib/libarcsoft_dualcam_refocus.so
git checkout -- proprietary/vendor/lib/libchromaflash.so
git checkout -- proprietary/vendor/lib/libedge_smooth_hvx_stub.so
git checkout -- proprietary/vendor/lib/libFaceGrade.so
git checkout -- proprietary/vendor/lib/libFaceProc.so
git checkout -- proprietary/vendor/lib/libflash_pmic.so
git checkout -- proprietary/vendor/lib/libjpegdhw.so
git checkout -- proprietary/vendor/lib/libjpegdmahw.so
git checkout -- proprietary/vendor/lib/libjpegehw.so
git checkout -- proprietary/vendor/lib/libmmcamera2_c2d_module.so
git checkout -- proprietary/vendor/lib/libmmcamera2_cpp_module.so
git checkout -- proprietary/vendor/lib/libmmcamera2_frame_algorithm.so
git checkout -- proprietary/vendor/lib/libmmcamera2_iface_modules.so
git checkout -- proprietary/vendor/lib/libmmcamera2_imglib_modules.so
git checkout -- proprietary/vendor/lib/libmmcamera2_is.so
git checkout -- proprietary/vendor/lib/libmmcamera2_isp_modules.so
git checkout -- proprietary/vendor/lib/libmmcamera2_mct.so
git checkout -- proprietary/vendor/lib/libmmcamera2_mct_shimlayer.so
git checkout -- proprietary/vendor/lib/libmmcamera2_pp_buf_mgr.so
git checkout -- proprietary/vendor/lib/libmmcamera2_pproc_modules.so
git checkout -- proprietary/vendor/lib/libmmcamera2_q3a_core.so
git checkout -- proprietary/vendor/lib/libmmcamera2_sensor_modules.so
git checkout -- proprietary/vendor/lib/libmmcamera2_stats_algorithm.so
git checkout -- proprietary/vendor/lib/libmmcamera2_stats_lib.so
git checkout -- proprietary/vendor/lib/libmmcamera2_stats_modules.so
git checkout -- proprietary/vendor/lib/libmmcamera_arcrtb_lib.so
git checkout -- proprietary/vendor/lib/libmmcamera_arcsoft_smoothtranstion_wrapper_lib.so
git checkout -- proprietary/vendor/lib/libmmcamera_chromaflash_lib.so
git checkout -- proprietary/vendor/lib/libmmcamera_csidtg.so
git checkout -- proprietary/vendor/lib/libmmcamera_dbg.so
git checkout -- proprietary/vendor/lib/libmmcamera_dummyalgo.so
git checkout -- proprietary/vendor/lib/libmmcamera_edgesmooth_lib.so
git checkout -- proprietary/vendor/lib/libmmcamera_eebinparse.so
git checkout -- proprietary/vendor/lib/libmmcamera_eeprom_util.so
git checkout -- proprietary/vendor/lib/libmmcamera_eztune_module.so
git checkout -- proprietary/vendor/lib/libmmcamera_facedetection_lib.so
git checkout -- proprietary/vendor/lib/libmmcamera_faceproc.so
git checkout -- proprietary/vendor/lib/libmmcamera_faceproc2.so
git checkout -- proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so
git checkout -- proprietary/vendor/lib/libmmcamera_hvx_add_constant.so
git checkout -- proprietary/vendor/lib/libmmcamera_hvx_grid_sum.so
git checkout -- proprietary/vendor/lib/libmmcamera_imglib.so
git checkout -- proprietary/vendor/lib/libmmcamera_llvd.so
git checkout -- proprietary/vendor/lib/libmmcamera_optizoom_lib.so
git checkout -- proprietary/vendor/lib/libmmcamera_paaf_lib.so
git checkout -- proprietary/vendor/lib/libmmcamera_pdaf.so
git checkout -- proprietary/vendor/lib/libmmcamera_pdafcamif.so
git checkout -- proprietary/vendor/lib/libmmcamera_ppbase_module.so
git checkout -- proprietary/vendor/lib/libmmcamera_quadracfa.so
git checkout -- proprietary/vendor/lib/libmmcamera_quadracfa.so
git checkout -- proprietary/vendor/lib/libmmcamera_sac_lib.so
git checkout -- proprietary/vendor/lib/libmmcamera_stillmore_lib.so
git checkout -- proprietary/vendor/lib/libmmcamera_sw2d_lib.so
git checkout -- proprietary/vendor/lib/libmmcamera_thread_services.so
git checkout -- proprietary/vendor/lib/libmmcamera_tintless_algo.so
git checkout -- proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so
git checkout -- proprietary/vendor/lib/libmmcamera_trueportrait_lib.so
git checkout -- proprietary/vendor/lib/libmmcamera_tuning.so
git checkout -- proprietary/vendor/lib/libmmcamera_tuning_lookup.so
git checkout -- proprietary/vendor/lib/libmmjpeg.so
git checkout -- proprietary/vendor/lib/libmmqjpeg_codec.so
git checkout -- proprietary/vendor/lib/libmmqjpegdma.so
git checkout -- proprietary/vendor/lib/libmorpho_easy_hdr.so
git checkout -- proprietary/vendor/lib/libmorpho_group_portrait.so
git checkout -- proprietary/vendor/lib/libmorpho_hdr_checker.so
git checkout -- proprietary/vendor/lib/libmorpho_panorama_gp.so
git checkout -- proprietary/vendor/lib/libmpbase.so
git checkout -- proprietary/vendor/lib/liboptizoom.so
git checkout -- proprietary/vendor/lib/libqomx_jpegdec.so
git checkout -- proprietary/vendor/lib/libqomx_jpegenc.so
git checkout -- proprietary/vendor/lib/libqomx_jpegenc_pipe.so
git checkout -- proprietary/vendor/lib/libRecoFace.so
git checkout -- proprietary/vendor/lib/libremosaic_daemon.so
git checkout -- proprietary/vendor/lib/libsac.so
git checkout -- proprietary/vendor/lib/libseemore.so
git checkout -- proprietary/vendor/lib/libStereoRectification.so
git checkout -- proprietary/vendor/lib/libtrueportrait.so
git checkout -- proprietary/vendor/lib/libubifocus.so
git checkout -- proprietary/vendor/lib/libactuator_ak7371_s5k3m3_semco.so
git checkout -- proprietary/vendor/lib/libactuator_ak7371.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_4k_preview_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_4k_video_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_common.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_cpp_hfr_120.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_cpp_hfr_60.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_cpp_hfr_90.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_cpp_liveshot.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_cpp_preview.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_cpp_snapshot.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_cpp_video.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_cpp_video_4k.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_default_preview_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_default_video.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_default_video_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_hfr_120.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_hfr_120_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_hfr_60.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_hfr_60_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_hfr_90.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_hfr_90_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_liveshot.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_postproc.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_preview.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_snapshot.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_video_4k.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_zsl_preview_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_imx268_zsl_video_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_4K_preview.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_4K_video.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_common.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_cpp_hfr_120.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_cpp_hfr_60.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_cpp_hfr_90.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_cpp_liveshot.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_cpp_preview.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_cpp_snapshot.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_cpp_snapshot_hdr.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_cpp_video.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_cpp_video_hdr.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_default_preview.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_default_video.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_hdr_snapshot_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_hdr_video_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_hfr_120.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_hfr_120_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_hfr_60.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_hfr_60_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_hfr_90.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_hfr_90_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_liveshot.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_postproc.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_preview.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_snapshot.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_snapshot_hdr.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_video.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_video_hdr.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_zsl_preview.so
git checkout -- proprietary/vendor/lib/libchromatix_imx386_semco_zsl_video.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_1080p_preview_ad5816g.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_1080p_video_ad5816g.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_4k_preview_ad5816g.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_4k_video_ad5816g.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_common.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_cpp_hfr_120.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_cpp_hfr_60.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_cpp_hfr_90.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_cpp_liveshot.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_cpp_preview.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_cpp_snapshot.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_cpp_snapshot_downscale.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_cpp_snapshot_upscale.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_cpp_video.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_cpp_video_4k.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_default_preview_ad5816g.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_default_video.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_default_video_ad5816g.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_hfr_120.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_hfr_120_ad5816g.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_hfr_60.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_hfr_60_ad5816g.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_hfr_90.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_hfr_90_ad5816g.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_liveshot.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_postproc.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_preview.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_snapshot.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_video_4k.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_zsl_preview_ad5816g.so
git checkout -- proprietary/vendor/lib/libchromatix_s5k3m3_semco_zsl_video_ad5816g.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_4k_preview_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_4k_video_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_common.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_cpp_hfr_120.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_cpp_hfr_60.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_cpp_hfr_90.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_cpp_liveshot.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_cpp_preview.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_cpp_snapshot.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_cpp_video.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_cpp_video_4k.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_default_preview_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_default_video.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_default_video_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_hfr_120.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_hfr_120_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_hfr_60.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_hfr_60_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_hfr_90.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_hfr_90_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_liveshot.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_postproc.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_preview.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_snapshot.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_video_4k.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_zsl_preview_3a.so
git checkout -- proprietary/vendor/lib/libchromatix_sagit_imx268_liteon_zsl_video_3a.so
git checkout -- proprietary/etc/camera/camera_config.xml
git checkout -- proprietary/etc/camera/imx386_semco_chromatix.xml
git checkout -- proprietary/etc/camera/s5k3m3_semco_chromatix.xml
git checkout -- proprietary/etc/camera/imx268_chromatix.xml
git checkout -- proprietary/etc/camera/sagit_imx268_liteon_chromatix.xml
git checkout -- proprietary/vendor/lib/libmmcamera_sagit_imx268_liteon_eeprom.so
git checkout -- proprietary/vendor/lib/libmmcamera_sagit_imx268_primax_eeprom.so
git checkout -- proprietary/vendor/lib/libmmcamera_sagit_imx386_semco_eeprom.so
git checkout -- proprietary/vendor/lib/libmmcamera_sagit_s5k3m3_semco_eeprom.so
git checkout -- proprietary/vendor/lib/libSonyIMX386PdafLibrary.so
git checkout -- proprietary/etc/firmware/cpp_firmware_v1_1_1.fw
git checkout -- proprietary/etc/firmware/cpp_firmware_v1_1_6.fw
git checkout -- proprietary/etc/firmware/cpp_firmware_v1_10_0.fw
git checkout -- proprietary/etc/firmware/cpp_firmware_v1_12_0.fw
git checkout -- proprietary/etc/firmware/cpp_firmware_v1_2_0.fw
git checkout -- proprietary/etc/firmware/cpp_firmware_v1_4_0.fw
git checkout -- proprietary/etc/firmware/cpp_firmware_v1_5_0.fw
git checkout -- proprietary/etc/firmware/cpp_firmware_v1_5_2.fw
git checkout -- proprietary/etc/firmware/cpp_firmware_v1_6_0.fw
git checkout -- proprietary/etc/firmware/cpp_firmware_v1_8_0.fw
git checkout -- proprietary/vendor/lib/libmmcamera_isp_abf48.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_abf48.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_aec_bg_stats47.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_bf_stats47.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_bg_stats46.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_bhist_stats44.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_black_level48.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_black_level48.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_bpc48.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_bpc48.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_cac47.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_chroma_enhan40.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_chroma_suppress40.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_clamp_encoder40.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_clamp_video40.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_color_correct46.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_color_xform_encoder46.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_color_xform_video46.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_color_xform_viewfinder46.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_cs_stats46.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_demosaic48.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_demosaic48.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_demux48.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_demux48.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_fovcrop_encoder46.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_fovcrop_video46.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_fovcrop_viewfinder46.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_gamma44.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_gic48.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_gic48.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_gtm46.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_hdr48.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_hdr48.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_hdr_be_stats46.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_hdr_bhist_stats44.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_hdr_bhist_stats44.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_ihist_stats46.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_linearization40.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_ltm47.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_mce40.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_mesh_rolloff44.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_pdaf48.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_pdaf48.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_pedestal_correct46.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_rs_stats46.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_scaler_encoder46.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_scaler_video46.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_scaler_viewfinder46.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_sce40.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_snr47.so
git checkout -- proprietary/vendor/lib/libmmcamera_isp_sub_module.so
git checkout -- proprietary/vendor/lib/libois_bu63164.so
git checkout -- proprietary/vendor/lib/libmmcamera_imx268.so
git checkout -- proprietary/vendor/lib/libmmcamera_imx386_semco.so
git checkout -- proprietary/vendor/lib/libmmcamera_s5k3m3_semco.so
git checkout -- proprietary/vendor/lib/libmmcamera_sagit_imx268_liteon.so
